### ISSUE TITLE
Express Session Error

### ISSUE THREAD

**Issue by kordnddn** [EckigerLuca/Darling#10]
Error: Login sessions require session support. Did you forget to use `express-session` middleware?
    at SessionStrategy.authenticate (/home/runner/Darling/node_modules/passport/lib/strategies/session.js:46:41)
    at attempt (/home/runner/Darling/node_modules/passport/lib/middleware/authenticate.js:369:16)
    at authenticate (/home/runner/Darling/node_modules/passport/lib/middleware/authenticate.js:370:7)
    at Layer.handle [as handle_request] (/home/runner/Darling/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/runner/Darling/node_modules/express/lib/router/index.js:328:13)
    at /home/runner/Darling/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/runner/Darling/node_modules/express/lib/router/index.js:346:12)
    at next (/home/runner/Darling/node_modules/express/lib/router/index.js:280:10)
    at initialize (/home/runner/Darling/node_modules/passport/lib/middleware/initialize.js:98:5)
    at Layer.handle [as handle_request] (/home/runner/Darling/node_modules/express/lib/router/layer.js:95:5)
Error: Login sessions require session support. Did you forget to use `express-session` middleware?
    at SessionStrategy.authenticate (/home/runner/Darling/node_modules/passport/lib/strategies/session.js:46:41)
    at attempt (/home/runner/Darling/node_modules/passport/lib/middleware/authenticate.js:369:16)
    at authenticate (/home/runner/Darling/node_modules/passport/lib/middleware/authenticate.js:370:7)
    at Layer.handle [as handle_request] (/home/runner/Darling/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/runner/Darling/node_modules/express/lib/router/index.js:328:13)
    at /home/runner/Darling/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/runner/Darling/node_modules/express/lib/router/index.js:346:12)
    at next (/home/runner/Darling/node_modules/express/lib/router/index.js:280:10)
    at initialize (/home/runner/Darling/node_modules/passport/lib/middleware/initialize.js:98:5)
    at Layer.handle [as handle_request] (/home/runner/Darling/node_modules/express/lib/router/layer.js:95:5)

**Comment by kordnddn** [comment]
help the error showed again

**Comment by kordnddn** [comment]
@EckigerLuca

**Comment by EckigerLuca** [comment]
Are all packages installed and updated? Did you change anything in the `index.js` of the webserver?

**Comment by kordnddn** [comment]
no i didnt
theres another error

┃ 2023-11-03 09:07:56:90 [ERROR]: AbortError: The user aborted a request.
    at abort (/home/runner/Darling/node_modules/node-fetch/lib/index.js:1458:16)
    at EventTarget.abortAndFinalize (/home/runner/Darling/node_modules/node-fetch/lib/index.js:1473:4)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:737:20)
    at EventTarget.dispatchEvent (node:internal/event_target:679:26)
    at abortSignal (node:internal/abort_controller:314:10)
    at AbortController.abort (node:internal/abort_controller:344:5)
    at Timeout._onTimeout (/home/runner/Darling/src/website/index.js:110:47)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  type: 'aborted'
}

**Comment by EckigerLuca** [comment]
To be honest, I don't really know what could cause this issue.
Is everything configured correctly? Have you tried to re-install all packages or even the bot?

**Comment by edwin-shdw** [comment]
@kordnddn Is the error reproducible? If so could you provide on how to reproduce it? It's kinda difficult on tracking down an error which does not exist. ([At least for luca](https://i.pinimg.com/1200x/71/ff/d4/71ffd47d032be54a1fad877bded70868.jpg))
