### ISSUE TITLE
Command isn't working, like no slash cmds showing

### ISSUE THREAD

**Issue by kordnddn** [EckigerLuca/Darling#9]

**Comment by EckigerLuca** [comment]
Did you deploy them using `npm run deploy`?

**Comment by kordnddn** [comment]
no, my bad thank you

**Comment by kordnddn** [comment]
Thank you, btw what this error? Error: Login sessions require session support. Did you forget to use `express-session` middleware?
    at SessionStrategy.authenticate (/home/runner/Darling/node_modules/passport/lib/strategies/session.js:46:41)
    at attempt (/home/runner/Darling/node_modules/passport/lib/middleware/authenticate.js:369:16)
    at authenticate (/home/runner/Darling/node_modules/passport/lib/middleware/authenticate.js:370:7)
    at Layer.handle [as handle_request] (/home/runner/Darling/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/runner/Darling/node_modules/express/lib/router/index.js:328:13)
    at /home/runner/Darling/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/runner/Darling/node_modules/express/lib/router/index.js:346:12)
    at next (/home/runner/Darling/node_modules/express/lib/router/index.js:280:10)
    at initialize (/home/runner/Darling/node_modules/passport/lib/middleware/initialize.js:98:5)
    at Layer.handle [as handle_request] (/home/runner/Darling/node_modules/express/lib/router/layer.js:95:5)
